name: micro_login
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  micro_core:
    git:
      url: https://github.com/gusttavovianna/micro_core.git
      ref: v1.0.0
  
  base_ui:
    git:
      url: https://github.com/gusttavovianna/base_ui.git
      ref: v1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true